thinkjotter/jotter/urls.py
from django.urls import path
from . import views


app_name = 'jotter'

urlpatterns = [
    path("", views.all_entries, name='all_entries'),
    path('new_entry/', views.new_entry, name='new_entry'),
    path('category_search/', views.category_search, name='category_search'),
    path('hashtag_search/', views.hashtag_search, name='hashtag_search'),
]

thinkjotter/thinkjotter/urls.py
from django.contrib import admin
from django.urls import include, path, reverse
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jotter/', include('jotter.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

thinkjotter/jotter/models.py
from django.db import models

class Entry(models.Model):
    date = models.DateField()
    literature = models.CharField(max_length=50, null=True, blank=True)
    notes = models.TextField()
    def __str__(self):
        return f'Journal entry on {self.date}'

class Hashtag(models.Model):
    tag = models.CharField(max_length=50, null=True, blank=True)
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE, related_name='tag')
    def __str__(self):
        return f'Hashtag #{self.tag}'

class Category(models.Model):
    category = models.CharField(max_length=50, null=True, blank=True, choices=[
                ('diary', 'diary'), 
                ('contemplation', 'contemplation'), 
                ('study / learning', 'study / learning'),
                ('meeting', 'meeting'), 
                ('professional', 'professional'),
                ('exercise log', 'exercise log'), 
                ('other', 'other')


            ]
        )
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE, related_name='category')
    def __str__(self):
        return f'Category {self.category}'

thinkjotter/jotter/forms.py
from django import forms
from .models import Entry, Category, Hashtag

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['date', 'notes', 'literature']
        labels = {'date': 'Date', 'notes': 'Notes', 'literature': 'References'}
        widgets = {'date': forms.DateInput(attrs={'type': 'date'}), 'notes': forms.Textarea(attrs={'cols': 80})}

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['category']
        labels = {'category': 'Category'}

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['tag']
        labels = {'tag': 'Hashtag'}

thinkjotter/jotter/views.py
from django.shortcuts import render
from jotter.models import Entry, Category, Hashtag
from django.urls import reverse
from django.http import HttpResponseRedirect
from .forms import EntryForm, CategoryForm, HashtagForm
import re

def new_entry(request):
    if request.method != 'POST':
        form1 = CategoryForm()
        form2 = EntryForm()
    else:
        form1 = CategoryForm(data=request.POST)
        form2 = EntryForm(data=request.POST)
        if form2.is_valid():
            form2.save()
        if form1.is_valid():
            entry = Entry.objects.last()
            category = Category(category=form1.cleaned_data['category'], entry_id=entry.id)
            category.save()
            hashtags = re.findall(r"#(\w+)", form2.cleaned_data['notes'])
            for tag in hashtags:
                hashtag = Hashtag(tag=tag, entry_id=entry.id)
                hashtag.save()
            return HttpResponseRedirect(reverse('jotter:all_entries'))
    context = {'form1': form1, 'form2': form2}
    return render(request, 'jotter/new_entry.html', context)

def all_entries(request):
    entries = Entry.objects.order_by('-date')
    context = {'entries': entries}
    return render(request, 'jotter/all_entries.html', context)

def category_search(request):
    if request.method != 'POST':
        form = CategoryForm()
    else:
        form = CategoryForm(data=request.POST)
        if form.is_valid():
            category = form.cleaned_data['category']
            entries = Entry.objects.filter(category__category=category).order_by('-date')
            context = {'entries': entries, 'category': category}
            return render(request, 'jotter/category_search.html', context)
    context = {'form': form}
    return render(request, 'jotter/category_search.html', context)

def hashtag_search(request):
    if request.method != 'POST':
        form = HashtagForm()
    else:
        form = HashtagForm(data=request.POST)
        if form.is_valid():
            tag = form.cleaned_data['tag']
            entries = Entry.objects.filter(tag__tag=tag).order_by('-date')
            context = {'entries': entries, 'tag': tag}
            return render(request, 'jotter/hashtag_search.html', context)
    context = {'form': form}
    return render(request, 'jotter/hashtag_search.html', context)

thinkjotter/jotter/templates/jotter/all_entries.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ThinkJotter</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    {% load static %}
   <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
   <style>
		a {
			color: black;
		}
    body {
      background-color: #f5f5f5;
    }
    .container {
      max-width: 700px;
      padding: 15px;
    }
    .side-container {
      float: left;
      width: 300px;
      margin-right: 30px;
			background-color: #dcdcdc;
			min-height: 100vh;
			margin-left: 30px;
    }
    h1, h2 {
      color: #286629;
      font-family: Arial, sans-serif;
      text-align: center;
      padding: 20px 0;
    }
		nav{
			margin-left: 20px;
		}
		p {
			padding: 10px;
		}
    .entry-date {
      color: #286629;
      font-size: 18px;
      font-style: italic;
    }
    .entry-notes {
      color: #555;
      margin-bottom: 10px;
    }
    .entry-literature {
      color: #999;
      font-style: italic;
      margin-bottom: 5px;
    }
   </style>
</head>
<body>
	<div class="container side-container">
    <nav>
        <li><a href="{% url 'jotter:all_entries' %}">All Entries</a></li>
				<li><a href="{% url 'jotter:category_search' %}">Search by Category</a></li>
				<li><a href="{% url 'jotter:hashtag_search' %}">Search by Hashtag</a></li>
        <li><a href="{% url 'jotter:new_entry' %}">Compose New Entry</a></li>
    </nav>
  </div>

<div class="container">
		<h1>Journal Entries</h1>
    {% for entry in entries %}
		<p>
        <div class="entry-date">{{ entry.date }}</div>
        <div class="entry-notes">{{ entry.notes }}</div>
				<div class="entry-literature">{% if entry.literature %}Literature:  {% endif %}
          {% if entry.literature %}{{ entry.literature }}{% endif %}</div>
    {% endfor %}
		</p>
</div>
<div class="footer">
    <p>ThinkJotter &copy; 2023</p>
</div>

</body>
</html>

thinkjotter/jotter/templates/jotter/category_search.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Search Results</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  {% load static %}
  <link rel="stylesheet" href="{% static 'bootstrap.min.css'}">
  <style>
    a {
			color: black;
		}
    body {
      background-color: #f5f5f5;
    }
    .container {
      max-width: 700px;
      padding: 15px;
    }
    .side-container {
      float: left;
      width: 300px;
      margin-right: 30px;
			background-color: #dcdcdc;
			min-height: 100vh;
			margin-left: 30px;
    }
    h1, h2 {
      color: #286629;
      font-family: Arial, sans-serif;
      text-align: center;
      padding: 20px 0;
    }
    form label {
      font-weight: bold;
    }
		nav{
			margin-left: 20px;
		}
		p {
			padding: 10px;
		}
    .entry-date {
      color: #286629;
      font-size: 18px;
      font-style: italic;
    }
    .entry-notes {
      color: #555;
      margin-bottom: 10px;
    }
    .entry-literature {
      color: #999;
      font-style: italic;
      margin-bottom: 5px;
    }
  </style>
</head>
<body>
    <div class="container side-container">
        <nav>
            <li><a href="{% url 'jotter:all_entries' %}">All Entries</a></li>
            <li><a href="{% url 'jotter:category_search' %}">Search by Category</a></li>
            <li><a href="{% url 'jotter:hashtag_search' %}">Search by Hashtag</a></li>
            <li><a href="{% url 'jotter:new_entry' %}">Compose New Entry</a></li>
        </nav>
    </div>
    <div class="container">
    <h1>Search Entries by Category</h1>
      <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          {% if form %}
          <input type="submit" value="Submit">
          {% endif %}
      </form>
 
		<h1>Journal Entries</h1>
        {% if entries|length != 0 %}
        {% for entry in entries %}
		<p>
      <div class="entry-date">{{ entry.date }}</div>
      <div class="entry-notes">{{ entry.notes }}</div>
			<div class="entry-literature">{% if entry.literature %}Literature: {{ entry.literature }}{% endif %}</div>
		</p>
        {% endfor %}
        {% else %}
    <p>No entries found.</p>
        {% endif %}
    </div>
</body>
</html>

thinkjotter/jotter/templates/jotter/hashtag_search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search Results</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css'}">
    <style>
    a {
			color: black;
		}
    body {
      background-color: #f5f5f5;
    }
    .container {
      max-width: 700px;
      padding: 15px;
    }
    .side-container {
      float: left;
      width: 300px;
      margin-right: 30px;
			background-color: #dcdcdc;
			min-height: 100vh;
			margin-left: 30px;
    }
    h1, h2 {
      color: #286629;
      font-family: Arial, sans-serif;
      text-align: center;
      padding: 20px 0;
    }
    form label {
      font-weight: bold;
    }
		nav{
			margin-left: 20px;
		}
		p {
			padding: 10px;
		}
    .entry-date {
      color: #286629;
      font-size: 18px;
      font-style: italic;
    }
    .entry-notes {
      color: #555;
      margin-bottom: 10px;
    }
    .entry-literature {
      color: #999;
      font-style: italic;
      margin-bottom: 5px;
    }
    </style>
</head>
<body>
    <div class="container side-container">
        <nav>
            <li><a href="{% url 'jotter:all_entries' %}">All Entries</a></li>
            <li><a href="{% url 'jotter:category_search' %}">Search by Category</a></li>
            <li><a href="{% url 'jotter:hashtag_search' %}">Search by Hashtag</a></li>
            <li><a href="{% url 'jotter:new_entry' %}">Compose New Entry</a></li>
        </nav>
    </div>
    <div class="container">
    <h1>Search Entries by Hashtag</h1>
      <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          {% if form %}
          <input type="submit" value="Submit">
          {% endif %}
      </form>
 
		<h1>Journal Entries</h1>
        {% if entries|length != 0 %}
        {% for entry in entries %}
		<p>
      <div class="entry-date">{{ entry.date }}</div>
      <div class="entry-notes">{{ entry.notes }}</div>
			<div class="entry-literature">{% if entry.literature %}Literature: {{ entry.literature }}{% endif %}</div>
		</p>
        {% endfor %}
        {% else %}
    <p>No entries found.</p>
        {% endif %}
    </div>
</body>
</html>

thinkjotter/jotter/templates/jotter/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>My Journal</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <style>
		a {
			color: black;
		}
    body {
      background-color: #f5f5f5;
    }
    .container {
      max-width: 700px;
      padding: 15px;
    }
    .side-container {
      float: left;
      width: 300px;
      margin-right: 30px;
			background-color: #dcdcdc;
			min-height: 100vh;
			margin-left: 30px;
    }
    h1, h2 {
      color: #286629;
      font-family: Arial, sans-serif;
      text-align: center;
      padding: 20px 0;
    }
    form label {
      font-weight: bold;
    }
		nav{
			margin-left: 20px;
    }
  </style>
</head>
<body>
	<div class="container side-container">
    <nav>
        <li><a href="{% url 'jotter:all_entries' %}">All Entries</a></li>
				<li>Search by Category</li>
				<li>Search by Hashtag</li>
        <li><a href="{% url 'jotter:new_entry' %}">Compose New Entry</a></li>
    </nav>
  </div>


  <div class="container" id="new_entry_form">
    <h1>Compose New Entry</h1>
      <form method="POST">
          {% csrf_token %}
          {{ form1.as_p }}
          {{ form2.as_p }}
          <input type="submit" value="Submit">
      </form>
  </div>
</body>
</html>